import Head from "next/head";
import React from "react";
import Navigation from "../components/Navigation/Navigation";

const DefaultLayout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Cats Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>{children}</main>
    </div>
  );
};

export default DefaultLayout;
